### PR TITLE
composer: allow PHP 8

### PR DESCRIPTION
**Pull request by TomasVotruba**
Hi,
I'm trying to update my blog to PHP 8 and these are last packages that block PHP version.

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Hi @TomasVotruba, could you run the test suite with 8.0?

**Comment by TomasVotruba** [comment]
Sure :+1: , I forgot to update those too.

**Comment by TomasVotruba** [comment]
Travis is passing :heavy_check_mark:

**Comment by Nielsvanpach** [comment]
To me it seems failed on your fork. 
The ✅ badge on this PR only shows StyleCI passed

**Comment by TomasVotruba** [comment]
So the CI here does not work? How can we fix that?

**Comment by freekmurze** [comment]
I'll take care of the tests, thanks!

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
