### PR TITLE
Add new parameter for external links #22

### PR DESCRIPTION
**Pull request by ilazaridis**

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test?

**Comment by ilazaridis** [comment]
I have added the test. Of course, it makes use of https://github.com/spatie/crawler/pull/51/commits/b44dac101cbe3e74bb01c1510826e2134e2980c2

**Comment by freekmurze** [comment]
Cool could you also add at test at the crawler repo?

**Comment by freekmurze** [comment]
Thanks again!

**Pull request merged**
